modLoader="javafml"

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="MIT License"

# A URL to refer people to when problems occur with this mod
issueTrackerURL= ""

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
modId="bosshealthregain" 
version="${file.jarVersion}"
displayName="bosshealthregain"
logoFile="bosshealthregain_logo.png"
credits="dragoni7"
authors="dragoni7" 
description='''
Allows bosses to regain their hp when players die nearby
'''
[[dependencies.bosshealthregain]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.forge]]
    modId = "forge"
    mandatory = true
    versionRange = "[43.1.1,)"
    ordering = "NONE"
    side = "BOTH"
